metricbeat.modules:
- module: jolokia
  metricsets: ["jmx"]
  enabled: true
  period: 10s
  hosts: ["localhost:9763"]
  namespace: "jvm"
  http_method: 'GET'
  jmx.mappings:
    - mbean: 'java.lang:type=Memory'
      attributes:
       - attr: HeapMemoryUsage
         field: memory.heap_usage
       - attr: NonHeapMemoryUsage
         field: memory.non_heap_usage
output.elasticsearch:
  hosts: 'wso2-elasticsearch-service'
  username: 'elastic'
  password: 'changeme'
output.elasticsearch.index: "${NODE_ID}-${NODE_IP}-metricbeat-%{+yyyy.MM.dd}"

setup.dashboards.index: "${NODE_ID}-${NODE_IP}-metricbeat-*"
setup.dashboards.enabled: true
setup.kibana:
  host: "wso2-kibana-service:5601"
setup.template.name: "${NODE_ID}-${NODE_IP}-metricbeat"
setup.template.pattern: "${NODE_ID}-${NODE_IP}-metricbeat-*"